# -*- coding: utf-8 -*-
"""use_model_colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tdw11uvErFJSfGBYf2vX0n0oarN-yk8T
"""

import numpy as np
import pickle

# mounting google drive to colab
from google.colab import drive
drive.mount('/content/drive')
!ls

# importing picle object from mounted drive
DATA_PATH = "/content/drive/My Drive/Data"
infile = open(DATA_PATH+'/classifier.pickle','rb')
classifier_colab = pickle.load(infile)

infile1 = open(DATA_PATH+'/sc.pickle','rb')
scaler_colab = pickle.load(infile1)

# list the files in colab
!ls

# remove files from colab
#!rm classifier.zip  sc.zip

# Predict
new_pred = classifier_colab.predict(scaler_colab.transform(np.array([[40,20000]])))
new_pred

new_pred_proba = classifier_colab.predict_proba(scaler_colab.transform(np.array([[40,20000]])))[:,1]
new_pred_proba

new_pred_2 = classifier_colab.predict(scaler_colab.transform(np.array([[42,50000]])))
new_pred_proba_2 = classifier_colab.predict_proba(scaler_colab.transform(np.array([[42,50000]])))[:,1]

new_pred_2

#new_pred_proba_2

#unmount Google drive
drive.flush_and_unmount()
print('All changes made in this colab session should now be visible in Drive.')